/**
 * Recent Moves — REAL Toro job photos only (no stock).
 * Source folder: Desktop/Toro-Work Images
 * Never use stock, AI ads, or third-party photos here.
 */

export type MoveService =
  | "full-service"
  | "apartment"
  | "residential"
  | "labor-only"
  | "packing"
  | "crew";

export type MoveShot = {
  id: string;
  src: string;
  alt: string;
  title: string;
  description: string;
  service: MoveService;
  serviceLabel: string;
  area: string;
  href: string;
};

export const recentMovesHeading = {
  eyebrow: "Recent moves",
  title: "See us in action",
  lead: "Real Toro Movers job photos—furniture protection, apartment carries, residential moves, and loading across Orlando and Central Florida.",
  cta: "View full gallery",
  ctaHref: "/orlando-movers-gallery",
} as const;

export const MOVE_SERVICE_ORDER: readonly {
  id: MoveService;
  label: string;
  href: string;
}[] = [
  { id: "full-service", label: "Full-service", href: "/full-service-moving" },
  { id: "apartment", label: "Apartment moves", href: "/apartment-movers-orlando-fl" },
  { id: "residential", label: "Residential / homes", href: "/residential-movers" },
  { id: "labor-only", label: "Labor-only / loading", href: "/labor-only-moving" },
  { id: "packing", label: "Packing & protection", href: "/full-service-moving" },
  { id: "crew", label: "Local crew", href: "/orlando-movers" },
] as const;

export const recentMoves: readonly MoveShot[] = [
  {
    id: "real-01",
    src: "/images/moves/real-01.jpg",
    alt: "Furniture fully stretch-wrapped and padded before a local move",
    title: "Furniture Protection — Stretch Wrap & Pads",
    description: "Toro Movers protects furniture with stretch wrap and pads on local Orlando and Central Florida jobs so pieces stay safe in transit.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-02",
    src: "/images/moves/real-02.jpg",
    alt: "Toro Movers real job photo 02 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-03",
    src: "/images/moves/real-03.jpg",
    alt: "Toro Movers real job photo 03 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-04",
    src: "/images/moves/real-04.jpg",
    alt: "Toro Movers real job photo 04 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-05",
    src: "/images/moves/real-05.jpg",
    alt: "Toro Movers real job photo 05 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-06",
    src: "/images/moves/real-06.jpg",
    alt: "Toro Movers real job photo 06 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-07",
    src: "/images/moves/real-07.jpg",
    alt: "Toro Movers crew moving a spa hot tub on a residential Central Florida job",
    title: "Specialty Residential Move — Hot Tub / Spa",
    description: "Residential movers handling oversized items carefully on a Central Florida home job—local crew, careful lifts, real work.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando, FL",
    href: "/residential-movers",
  },
  {
    id: "real-08",
    src: "/images/moves/real-08.jpg",
    alt: "Toro Movers real job photo 08 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-09",
    src: "/images/moves/real-09.jpg",
    alt: "Toro Movers real job photo 09 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-10",
    src: "/images/moves/real-10.jpg",
    alt: "Toro Movers real job photo 10 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-11",
    src: "/images/moves/real-11.jpg",
    alt: "Toro Movers real job photo 11 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-12",
    src: "/images/moves/real-12.jpg",
    alt: "Toro Movers real job photo 12 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-13",
    src: "/images/moves/real-13.jpg",
    alt: "Toro Movers real job photo 13 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-14",
    src: "/images/moves/real-14.jpg",
    alt: "Wrapped furniture staged during an apartment move with Toro Movers",
    title: "Apartment Placement — Protected Furniture",
    description: "Apartment movers wrap sofas and seating for safe carries through hallways and elevators on Orlando-area jobs.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-15",
    src: "/images/moves/real-15.jpg",
    alt: "Toro Movers real job photo 15 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-16",
    src: "/images/moves/real-16.jpg",
    alt: "Toro Movers real job photo 16 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-17",
    src: "/images/moves/real-17.jpg",
    alt: "Toro Movers real job photo 17 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-18",
    src: "/images/moves/real-18.jpg",
    alt: "Toro Movers real job photo 18 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-19",
    src: "/images/moves/real-19.jpg",
    alt: "Toro Movers real job photo 19 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-20",
    src: "/images/moves/real-20.jpg",
    alt: "Toro Movers real job photo 20 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-21",
    src: "/images/moves/real-21.jpg",
    alt: "Toro Movers real job photo 21 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-22",
    src: "/images/moves/real-22.jpg",
    alt: "Toro Movers real job photo 22 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-23",
    src: "/images/moves/real-23.jpg",
    alt: "Toro Movers real job photo 23 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-24",
    src: "/images/moves/real-24.jpg",
    alt: "Toro Movers real job photo 24 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-25",
    src: "/images/moves/real-25.jpg",
    alt: "Toro Movers real job photo 25 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-26",
    src: "/images/moves/real-26.jpg",
    alt: "Toro Movers crew carrying boxes in an apartment hallway on a local move",
    title: "Apartment Hallway Load — Orlando Area",
    description: "Apartment movers stack and carry boxes through common hallways carefully on Orlando and Central Florida jobs.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-27",
    src: "/images/moves/real-27.jpg",
    alt: "Toro Movers real job photo 27 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-28",
    src: "/images/moves/real-28.jpg",
    alt: "Toro Movers real job photo 28 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-29",
    src: "/images/moves/real-29.jpg",
    alt: "Toro Movers real job photo 29 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-30",
    src: "/images/moves/real-30.jpg",
    alt: "Toro Movers real job photo 30 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-31",
    src: "/images/moves/real-31.jpg",
    alt: "Toro Movers real job photo 31 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-32",
    src: "/images/moves/real-32.jpg",
    alt: "Toro Movers real job photo 32 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-33",
    src: "/images/moves/real-33.jpg",
    alt: "Toro Movers real job photo 33 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-34",
    src: "/images/moves/real-34.jpg",
    alt: "Toro Movers real job photo 34 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-35",
    src: "/images/moves/real-35.jpg",
    alt: "Toro Movers real job photo 35 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-36",
    src: "/images/moves/real-36.jpg",
    alt: "Toro Movers real job photo 36 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-37",
    src: "/images/moves/real-37.jpg",
    alt: "Toro Movers real job photo 37 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-38",
    src: "/images/moves/real-38.jpg",
    alt: "Toro Movers crew member stretch-wrapping furniture on an apartment move",
    title: "Crew Wrap & Protect — Apartment Move",
    description: "Local bilingual crew wraps furniture on site—professional protection for apartment and home moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-39",
    src: "/images/moves/real-39.jpg",
    alt: "Toro Movers real job photo 39 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-40",
    src: "/images/moves/real-40.jpg",
    alt: "Toro Movers real job photo 40 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-41",
    src: "/images/moves/real-41.jpg",
    alt: "Toro Movers real job photo 41 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-42",
    src: "/images/moves/real-42.jpg",
    alt: "Toro Movers real job photo 42 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-43",
    src: "/images/moves/real-43.jpg",
    alt: "Toro Movers real job photo 43 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-44",
    src: "/images/moves/real-44.jpg",
    alt: "Toro Movers real job photo 44 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-45",
    src: "/images/moves/real-45.jpg",
    alt: "Toro Movers real job photo 45 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-46",
    src: "/images/moves/real-46.jpg",
    alt: "Toro Movers real job photo 46 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-47",
    src: "/images/moves/real-47.jpg",
    alt: "Toro Movers real job photo 47 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
] as const;

export const recentMovesHome = recentMoves.slice(0, 8);

export function recentMovesByService(): {
  id: MoveService;
  label: string;
  href: string;
  items: MoveShot[];
}[] {
  return MOVE_SERVICE_ORDER.map((s) => ({
    id: s.id,
    label: s.label,
    href: s.href,
    items: recentMoves.filter((m) => m.service === s.id) as MoveShot[],
  })).filter((g) => g.items.length > 0);
}

export const recentMovesPageMeta = {
  title: "Orlando Movers Gallery | Real Job Photos",
  description: "Real Toro Movers job photos from Orlando and Central Florida—apartment moves, home moves, packing, and loading. Family-owned local crew. No stock photos.",
  path: "/orlando-movers-gallery",
  h1: "Orlando movers gallery",
  sub: "Real job photos from local moves",
} as const;
