/**
 * Recent Moves — REAL Toro job photos only (no stock).
 * Source folder: Desktop/Toro-Work Images
 * Never use stock, AI ads, or third-party photos here.
 */

export type MoveService =
  | "full-service"
  | "apartment"
  | "residential"
  | "labor-only"
  | "packing"
  | "crew";

export type MoveShot = {
  id: string;
  src: string;
  alt: string;
  title: string;
  description: string;
  service: MoveService;
  serviceLabel: string;
  area: string;
  href: string;
};

export const recentMovesHeading = {
  eyebrow: "Recent moves",
  title: "See us in action",
  lead: "Real Toro Movers job photos—furniture protection, apartment carries, residential moves, and loading across Orlando and Central Florida.",
  cta: "View full gallery",
  ctaHref: "/orlando-movers-gallery",
} as const;

export const MOVE_SERVICE_ORDER: readonly {
  id: MoveService;
  label: string;
  href: string;
}[] = [
  { id: "full-service", label: "Full-service", href: "/full-service-moving" },
  { id: "apartment", label: "Apartment moves", href: "/apartment-movers-orlando-fl" },
  { id: "residential", label: "Residential / homes", href: "/residential-movers" },
  { id: "labor-only", label: "Labor-only / loading", href: "/labor-only-moving" },
  { id: "packing", label: "Packing & protection", href: "/full-service-moving" },
  { id: "crew", label: "Local crew", href: "/orlando-movers" },
] as const;

export const recentMoves: readonly MoveShot[] = [
  {
    id: "real-01",
    src: "/images/moves/real-01.webp",
    alt: "Furniture fully stretch-wrapped and padded before a local move",
    title: "Furniture Protection — Stretch Wrap & Pads",
    description: "Toro Movers protects furniture with stretch wrap and pads on local Orlando and Central Florida jobs so pieces stay safe in transit.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-02",
    src: "/images/moves/real-02.webp",
    alt: "Toro Movers real job photo 02 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-03",
    src: "/images/moves/real-03.webp",
    alt: "Toro Movers real job photo 03 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-04",
    src: "/images/moves/real-04.webp",
    alt: "Toro Movers real job photo 04 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-05",
    src: "/images/moves/real-05.webp",
    alt: "Toro Movers real job photo 05 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-09",
    src: "/images/moves/real-09.webp",
    alt: "Toro Movers real job photo 09 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-10",
    src: "/images/moves/real-10.webp",
    alt: "Toro Movers real job photo 10 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-11",
    src: "/images/moves/real-11.webp",
    alt: "Toro Movers real job photo 11 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-12",
    src: "/images/moves/real-12.webp",
    alt: "Toro Movers real job photo 12 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-13",
    src: "/images/moves/real-13.webp",
    alt: "Toro Movers real job photo 13 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-14",
    src: "/images/moves/real-14.webp",
    alt: "Wrapped furniture staged during an apartment move with Toro Movers",
    title: "Apartment Placement — Protected Furniture",
    description: "Apartment movers wrap sofas and seating for safe carries through hallways and elevators on Orlando-area jobs.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-15",
    src: "/images/moves/real-15.webp",
    alt: "Toro Movers real job photo 15 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-16",
    src: "/images/moves/real-16.webp",
    alt: "Toro Movers real job photo 16 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-17",
    src: "/images/moves/real-17.webp",
    alt: "Toro Movers real job photo 17 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-18",
    src: "/images/moves/real-18.webp",
    alt: "Toro Movers real job photo 18 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-19",
    src: "/images/moves/real-19.webp",
    alt: "Toro Movers real job photo 19 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-20",
    src: "/images/moves/real-20.webp",
    alt: "Toro Movers real job photo 20 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-21",
    src: "/images/moves/real-21.webp",
    alt: "Toro Movers real job photo 21 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-22",
    src: "/images/moves/real-22.webp",
    alt: "Toro Movers real job photo 22 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-23",
    src: "/images/moves/real-23.webp",
    alt: "Toro Movers real job photo 23 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-24",
    src: "/images/moves/real-24.webp",
    alt: "Toro Movers real job photo 24 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-25",
    src: "/images/moves/real-25.webp",
    alt: "Toro Movers real job photo 25 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-28",
    src: "/images/moves/real-28.webp",
    alt: "Toro Movers real job photo 28 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-29",
    src: "/images/moves/real-29.webp",
    alt: "Toro Movers real job photo 29 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-30",
    src: "/images/moves/real-30.webp",
    alt: "Toro Movers real job photo 30 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-33",
    src: "/images/moves/real-33.webp",
    alt: "Toro Movers real job photo 33 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-34",
    src: "/images/moves/real-34.webp",
    alt: "Toro Movers real job photo 34 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-35",
    src: "/images/moves/real-35.webp",
    alt: "Toro Movers real job photo 35 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-36",
    src: "/images/moves/real-36.webp",
    alt: "Toro Movers real job photo 36 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-38",
    src: "/images/moves/real-38.webp",
    alt: "Toro Movers crew member stretch-wrapping furniture on an apartment move",
    title: "Crew Wrap & Protect — Apartment Move",
    description: "Local bilingual crew wraps furniture on site—professional protection for apartment and home moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-39",
    src: "/images/moves/real-39.webp",
    alt: "Toro Movers real job photo 39 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-40",
    src: "/images/moves/real-40.webp",
    alt: "Toro Movers real job photo 40 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-41",
    src: "/images/moves/real-41.webp",
    alt: "Toro Movers real job photo 41 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
  {
    id: "real-42",
    src: "/images/moves/real-42.webp",
    alt: "Toro Movers real job photo 42 — local moving work in Orlando metro",
    title: "Local crew on the job — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "crew",
    serviceLabel: "Local crew",
    area: "Orlando metro",
    href: "/orlando-movers",
  },
  {
    id: "real-43",
    src: "/images/moves/real-43.webp",
    alt: "Toro Movers real job photo 43 — local moving work in Orlando, FL",
    title: "Full-service local move — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "full-service",
    serviceLabel: "Full-service moving",
    area: "Orlando, FL",
    href: "/full-service-moving",
  },
  {
    id: "real-44",
    src: "/images/moves/real-44.webp",
    alt: "Toro Movers real job photo 44 — local moving work in Central Florida",
    title: "Apartment move — Orlando area — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "apartment",
    serviceLabel: "Apartment moving",
    area: "Central Florida",
    href: "/apartment-movers-orlando-fl",
  },
  {
    id: "real-45",
    src: "/images/moves/real-45.webp",
    alt: "Toro Movers real job photo 45 — local moving work in Orlando metro",
    title: "Residential home move — Orlando metro",
    description: "Real Toro Movers work on a local job in Orlando metro. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "residential",
    serviceLabel: "Residential moving",
    area: "Orlando metro",
    href: "/residential-movers",
  },
  {
    id: "real-46",
    src: "/images/moves/real-46.webp",
    alt: "Toro Movers real job photo 46 — local moving work in Orlando, FL",
    title: "Loading & unloading — Orlando, FL",
    description: "Real Toro Movers work on a local job in Orlando, FL. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "labor-only",
    serviceLabel: "Labor-only / loading",
    area: "Orlando, FL",
    href: "/labor-only-moving",
  },
  {
    id: "real-47",
    src: "/images/moves/real-47.webp",
    alt: "Toro Movers real job photo 47 — local moving work in Central Florida",
    title: "Furniture protection — Central Florida",
    description: "Real Toro Movers work on a local job in Central Florida. Family-owned Orlando and Central Florida movers for full-service, labor-only, apartment, and residential moves.",
    service: "packing",
    serviceLabel: "Packing & protection",
    area: "Central Florida",
    href: "/full-service-moving",
  },
] as const;

/** Homepage: only 6 thumbnails to keep LCP fast */
export const recentMovesHome = recentMoves.slice(0, 6);

export function recentMovesByService(): {
  id: MoveService;
  label: string;
  href: string;
  items: MoveShot[];
}[] {
  return MOVE_SERVICE_ORDER.map((s) => ({
    id: s.id,
    label: s.label,
    href: s.href,
    items: recentMoves.filter((m) => m.service === s.id) as MoveShot[],
  })).filter((g) => g.items.length > 0);
}

export const recentMovesPageMeta = {
  title: "Orlando Movers Gallery | Real Job Photos",
  description: "Real Toro Movers job photos from Orlando and Central Florida—apartment moves, home moves, packing, and loading. Family-owned local crew. No stock photos.",
  path: "/orlando-movers-gallery",
  h1: "Orlando movers gallery",
  sub: "Real job photos from local moves",
} as const;
