import Link from "next/link";
import UniversalLeadForm from "@/components/funnel/UniversalLeadForm";

export const metadata = {
  title: "Local Movers in Central Florida | Free Quote | Toro Movers",
  description: "Get a free quote from Toro Movers for local moving, labor-only help, rental truck loading, PODs, and more in Central Florida.",
};

const services = [
  "Full-service moves with truck and movers",
  "Labor-only loading and unloading",
  "Same-building apartment and condo moves",
  "Special-item and single-item moves",
  "POD, container, U-Haul, and rental-truck help",
];

export default function LocalMoversLandingPage() {
  return <main className="min-h-screen bg-zinc-50 text-zinc-950">
    <header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4"><Link href="/" className="text-lg font-black tracking-tight">TORO MOVERS</Link><a className="font-bold underline underline-offset-4" href="tel:+13217580094">Call (321) 758-0094</a></div></header>
    <section className="overflow-hidden bg-black text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:py-24"><div><p className="mb-4 inline-flex rounded-full border border-white/25 px-3 py-1 text-sm font-bold">★★★★★ 5.0 • Central Florida</p><h1 className="max-w-3xl text-4xl font-black leading-tight tracking-tight sm:text-6xl">Reliable Central Florida Movers. Get Your Free Quote Today.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-300">From full-service moves to loading help, rental trucks, PODs, and single-item moves, Toro Movers makes it easy to get the right moving support.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#quote-form" className="rounded-xl bg-white px-6 py-4 font-extrabold text-black transition hover:bg-zinc-200">Get My Free Quote</a><a href="tel:+13217580094" className="rounded-xl border border-white/40 px-6 py-4 font-extrabold transition hover:bg-white/10">Call Now</a></div><p className="mt-5 text-sm text-zinc-400">No obligation • Choose your service in under a minute</p></div><div className="rounded-3xl bg-zinc-900 p-8 ring-1 ring-white/10"><p className="text-sm font-bold uppercase tracking-widest text-zinc-400">Moving help that fits your move</p><ul className="mt-5 space-y-4">{services.map((service) => <li key={service} className="flex gap-3 text-lg"><span aria-hidden>✓</span><span>{service}</span></li>)}</ul></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-14 lg:py-20"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="text-sm font-extrabold uppercase tracking-widest text-zinc-500">Get started</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Tell us what kind of move you need.</h2><p className="mt-4 leading-7 text-zinc-600">Choose your service, answer a few quick questions, and send your request. We will use the details to prepare the right next step.</p><div className="mt-8 grid gap-4 sm:grid-cols-3 lg:grid-cols-1">{[["1", "Choose service"], ["2", "Add move details"], ["3", "Get connected"]].map(([number, label]) => <div key={number} className="flex items-center gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-zinc-200"><span className="grid h-8 w-8 place-items-center rounded-full bg-black text-sm font-black text-white">{number}</span><span className="font-bold">{label}</span></div>)}</div></div><UniversalLeadForm source="local_movers_ads_landing" /></div></section>
    <section className="border-y border-zinc-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-16"><p className="text-sm font-extrabold uppercase tracking-widest text-zinc-500">Why Toro Movers</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight">A straightforward way to get moving help without a complicated quote process.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="rounded-2xl bg-zinc-50 p-6"><h3 className="font-extrabold">Choose the right service</h3><p className="mt-2 text-zinc-600">Full-service, labor-only, container, rental-truck, special-item, and small-move options in one quote flow.</p></article><article className="rounded-2xl bg-zinc-50 p-6"><h3 className="font-extrabold">Share the details that matter</h3><p className="mt-2 text-zinc-600">Your move details help the team understand access, timing, locations, and scope before following up.</p></article><article className="rounded-2xl bg-zinc-50 p-6"><h3 className="font-extrabold">Get a clear next step</h3><p className="mt-2 text-zinc-600">Send your request online or call the team directly when you need help right away.</p></article></div></div></section>
    <footer className="bg-black px-5 py-10 text-center text-white"><p className="text-2xl font-black">Ready to plan your move?</p><div className="mt-5 flex flex-wrap justify-center gap-4"><a href="#quote-form" className="rounded-xl bg-white px-6 py-4 font-extrabold text-black">Get My Free Quote</a><a href="tel:+13217580094" className="rounded-xl border border-white/40 px-6 py-4 font-extrabold">Call (321) 758-0094</a></div></footer>
  </main>;
}
